 <!-- Copyright (C) 2009 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Shaopeng Jia

     Metadata on Phone Number Plan and formatting rules
     Note: Territories are in alphabetical order by their IDs, which are based on CLDR
           two-letter region codes (or are set to "001" for non-geographical entities, which
           represents "World" in the UN M.49 standard). The country names in the comments are the
           official short names in English according to CLDR.

     For more information on what each element represents, see
     resources/phonemetadata.proto

     Note that if you want to add validation metadata, the generalDesc nationalNumberPattern must be
     provided. If this is missing, then the country will be considered to have no more specific
     phone-number type metadata (fixedLine, mobile etc) and hence only basic validation rules
     (numbers should be between 3 and 15 digits long) will be applied.

     If adding an element for a non-geographical entity, please add an example number element to the
     general description.

     Country code, international and national prefix information main source:
     http://www.itu.int/pub/T-SP-E.164C-2011

     Known omissions:
     * French Southern Territories (id="TF" countryCode="262")
       This is not covered due to lack of information about its numbering plan. It has 140
       temporary inhabitants.

     * Pitcairn Island (id="PN")
       This is not supported since evidence seems to be that the 50 inhabitants use satellite
       phones.

     See also:
       https://github.com/google/libphonenumber/blob/master/FAQ.md#unsupported
     -->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (references?, availableFormats?, generalDesc, noInternationalDialling?,
        fixedLine?, mobile?, pager?, tollFree?, premiumRate?,
        sharedCost?, personalNumber?, voip?, uan?, voicemail?)>
    <!ELEMENT references (sourceUrl+)>
    <!ELEMENT generalDesc (nationalNumberPattern)>
    <!ELEMENT noInternationalDialling (possibleLengths, nationalNumberPattern)>
    <!ELEMENT fixedLine (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT mobile (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT pager (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT tollFree (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT premiumRate (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT sharedCost (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT personalNumber (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT voip (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT uan (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT voicemail (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT sourceUrl (#PCDATA)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>
    <!ELEMENT leadingDigits (#PCDATA)>
    <!ELEMENT possibleLengths EMPTY>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory mainCountryForCode (true) #IMPLIED>
    <!ATTLIST territory leadingDigits CDATA #IMPLIED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST territory carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory mobileNumberPortableRegion (true) #IMPLIED>
    <!ATTLIST possibleLengths national CDATA #REQUIRED>
    <!ATTLIST possibleLengths localOnly CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST numberFormat carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Ascension Island (AC) -->
    <!-- http://www.itu.int/oth/T02020000AF/en -->
    <territory id="AC" countryCode="247" internationalPrefix="00">
      <generalDesc>
        <nationalNumberPattern>
          (?:
            [01589]\d|
            [46]
          )\d{4}
        </nationalNumberPattern>
      </generalDesc>
      <!-- Note prefix 4 is reserved for mobile use , not currently in use -->
      <mobile>
        <possibleLengths national="5"/>
        <exampleNumber>40123</exampleNumber>
        <nationalNumberPattern>4\d{4}</nationalNumberPattern>
      </mobile>
      <!-- Omit '00' as a prefix since that's the IDD prefix. -->
    </territory>

    <!-- Andorra (AD) -->
    <!-- http://www.itu.int/oth/T0202000005/en -->
    <territory id="AD" countryCode="376" internationalPrefix="00">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{3})">
          <leadingDigits>[135-9]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{4})">
          <leadingDigits>1</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{3})">
          <leadingDigits>6</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          (?:
            1|
            6\d
          )\d{7}|
          [135-9]\d{5}
        </nationalNumberPattern>
      </generalDesc>
      <noInternationalDialling>
        <possibleLengths national="8"/>
        <nationalNumberPattern>1800\d{4}</nationalNumberPattern>
      </noInternationalDialling>
      <mobile>
        <possibleLengths national="6,9"/>
        <exampleNumber>312345</exampleNumber>
        <nationalNumberPattern>
          690\d{6}|
          [356]\d{5}
        </nationalNumberPattern>
      </mobile>
      <!-- Note that the definitions of 1800 and 1802 numbers differ in the plan and on the
           Andorran http://www.sta.ad website, but we consider both to be freephone here. -->
      <!-- The national numbering plan says that 6-digit numbers beginning with 1 and 9 are reserved
           for special services, so we assume they are premium rate here, although we cannot find
           examples online. -->
    </territory>

    <!-- United Arab Emirates (AE) -->
    <!-- http://www.itu.int/oth/T02020000DC/en -->
    <territory id="AE" countryCode="971" internationalPrefix="00" nationalPrefix="0">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{2,9})">
          <leadingDigits>
            60|
            8
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d)(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            [236]|
            [479][2-8]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d)(\d{5})">
          <leadingDigits>[479]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>5</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          (?:
            [4-7]\d|
            9[0-689]
          )\d{7}|
          800\d{2,9}|
          [2-4679]\d{7}
        </nationalNumberPattern>
      </generalDesc>
      <!-- Prefixes 54 and 58 are mentioned on Wikipedia,
           https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates. -->
      <mobile>
        <possibleLengths national="9"/>
        <exampleNumber>501234567</exampleNumber>
        <nationalNumberPattern>5[024-68]\d{7}</nationalNumberPattern>
      </mobile>
    </territory>

    <!-- Afghanistan (AF) -->
    <!-- http://www.itu.int/oth/T0202000001/en -->
    <territory id="AF" countryCode="93" internationalPrefix="00" nationalPrefix="0">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{4})">
          <leadingDigits>[1-9]</leadingDigits>
          <format>$1 $2</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
        <!-- Formatting based primarily on ITU document. -->
        <numberFormat pattern="(\d{2})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>[2-7]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[2-7]\d{8}</nationalNumberPattern>
      </generalDesc>
      <!-- 731 range is supported based on user report. -->
      <mobile>
        <possibleLengths national="9" localOnly="7"/>
        <exampleNumber>701234567</exampleNumber>
        <nationalNumberPattern>7\d{8}</nationalNumberPattern>
      </mobile>
    </territory>

    <!-- Antigua & Barbuda (AG) -->
    <!-- Calling code and formatting shared with 'US' -->
    <!-- http://www.itu.int/oth/T0202000008/en -->
    <territory id="AG" countryCode="1" leadingDigits="268" internationalPrefix="011"
               nationalPrefix="1" nationalPrefixForParsing="1|([457]\d{6})$"
               nationalPrefixTransformRule="268$1" mobileNumberPortableRegion="true">
      <generalDesc>
        <nationalNumberPattern>
          (?:
            268|
            [58]\d\d|
            900
          )\d{7}
        </nationalNumberPattern>
      </generalDesc>
      <!-- 268 468 is not in the plan, but has been added after numbers with this prefix have been
           found in online searches. -->
      <!-- 268 776/778/779 are not in the plan, but have been added after numbers with these
           prefixes have been found in online searches. Same for 268 782/784/786/789. -->
      <mobile>
        <possibleLengths national="10" localOnly="7"/>
        <exampleNumber>2684641234</exampleNumber>
        <nationalNumberPattern>
          268(?:
            464|
            7(?:
              1[3-9]|
              [28]\d|
              3[0246]|
              64|
              7[0-689]
            )
          )\d{4}
        </nationalNumberPattern>
      </mobile>
      <!-- https://www.nationalnanpa.com/number_resource_info/5XX_codes.html -->
      <!-- This is included as Centrex in the plan. -->
    </territory>

    <!-- Anguilla (AI) -->
    <!-- Calling code and formatting shared with 'US' -->
    <!-- http://www.itu.int/oth/T0202000007/en -->
    <territory id="AI" countryCode="1" leadingDigits="264" internationalPrefix="011"
               nationalPrefix="1" nationalPrefixForParsing="1|([2457]\d{6})$"
               nationalPrefixTransformRule="264$1" mobileNumberPortableRegion="true">
      <generalDesc>
        <nationalNumberPattern>
          (?:
            264|
            [58]\d\d|
            900
          )\d{7}
        </nationalNumberPattern>
      </generalDesc>
      <mobile>
        <possibleLengths national="10" localOnly="7"/>
        <exampleNumber>2642351234</exampleNumber>
        <nationalNumberPattern>
          264(?:
            235|
            4(?:
              69|
              76
            )|
            5(?:
              3[6-9]|
              8[1-4]
            )|
            7(?:
              29|
              72
            )
          )\d{4}
        </nationalNumberPattern>
      </mobile>
      <!-- https://www.nationalnanpa.com/number_resource_info/5XX_codes.html -->
    </territory>

    <!-- Albania (AL) -->
    <!-- http://www.itu.int/oth/T0202000002/en -->
    <territory id="AL" countryCode="355" internationalPrefix="00" nationalPrefix="0"
               mobileNumberPortableRegion="true">
      <availableFormats>
        <!-- Premium rate or toll free formats -->
        <numberFormat pattern="(\d{3})(\d{3,4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            80|
            9
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- Formats mostly follow http://tirana.usembassy.gov/list_of_doctors.html -->
        <numberFormat pattern="(\d)(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>4[2-6]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{3})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            [2358][2-5]|
            4
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{5})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>[23578]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>6</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          (?:
            700\d\d|
            900
          )\d{3}|
          8\d{5,7}|
          (?:
            [2-5]|
            6\d
          )\d{7}
        </nationalNumberPattern>
      </generalDesc>
      <!-- More specific prefixes from the 1.NumraAlokuar.rar file linked from the ITU doc.
           Though 677 is mentioned as unallocated in
           http://akep.al/images/stories/AKEP/plani-numracionit/1.NumraAlokuar.rar,
           adding support for 67[7-9] based on carrier doc. -->
      <mobile>
        <possibleLengths national="9"/>
        <exampleNumber>672123456</exampleNumber>
        <nationalNumberPattern>
          6(?:
            [78][2-9]|
            9\d
          )\d{6}
        </nationalNumberPattern>
      </mobile>
      <!-- It is named "Shared Revenue Services" in the plan, but as there is a separate "Shared
           Cost Services", it is highly likely these numbers are premium rate numbers. No
           information/example is found in the Internet. -->
    </territory>

    <!-- Armenia (AM) -->
    <!-- We think the national dialling prefix is 0 - it seems this was a change in 2005 (or 2008)
         along with the new city codes. However, their official document makes no mention of it,
         websites disagree, and we are not sure if the change has actually been made. -->
    <!-- http://www.itu.int/oth/T020200000A/en -->
    <!-- http://en.wikipedia.org/wiki/%2B374 -->
    <!-- http://en.wikipedia.org/wiki/Telephone_numbers_in_Nagorno-Karabakh_Republic -->
    <territory id="AM" countryCode="374" internationalPrefix="00" nationalPrefix="0"
               mobileNumberPortableRegion="true">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{2})(\d{3})" nationalPrefixFormattingRule="$NP $FG">
          <leadingDigits>[89]0</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{5})" nationalPrefixFormattingRule="($NP$FG)">
          <leadingDigits>
            2|
            3[12]
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{6})" nationalPrefixFormattingRule="($NP$FG)">
          <leadingDigits>
            1|
            47
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{6})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>[3-9]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          (?:
            [1-489]\d|
            55|
            60|
            77
          )\d{6}
        </nationalNumberPattern>
      </generalDesc>
      <!-- Includes telephone numbers in Nagorno-Karabakh Republic, physically located inside
           Azerbaijan, which use prefix 47. -->
      <!-- Part of the range 97 is used by Nagorno-Karabakh Republic. -->
      <mobile>
        <possibleLengths national="8"/>
        <exampleNumber>77123456</exampleNumber>
        <nationalNumberPattern>
          (?:
            33|
            4[1349]|
            55|
            77|
            88|
            9[13-9]
          )\d{6}
        </nationalNumberPattern>
      </mobile>
    </territory>

    <!-- Angola (AO) -->
    <!-- http://www.itu.int/oth/T0202000006/en -->
    <territory id="AO" countryCode="244" internationalPrefix="00">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{3})(\d{3})">
          <leadingDigits>[29]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[29]\d{8}</nationalNumberPattern>
      </generalDesc>
      <!-- Supporting 2Y5 and 2YY5 ranges (where Y and YY represent one and two digit area code)
           based on user report and format followed in ITU doc. Wikipedia also mentions that
           "Fixed-line numbers start with digit 2, followed by 1 or 2 digits area code. After the
           area code, there is one digit telecoms operator code. So now we are adding 5 as telecom
           operator code now." -->
      <!-- Expanded the 92 prefix possibilities to match numbers found online. Unitel
           apparently launched the prefix 94 on 25th April 2012, and Movicel has 99. -->
      <mobile>
        <possibleLengths national="9"/>
        <exampleNumber>923123456</exampleNumber>
        <nationalNumberPattern>9[1-59]\d{7}</nationalNumberPattern>
      </mobile>
    </territory>

    <!-- Argentina (AR) -->
    <!-- The national prefix for parsing here consists of a 0 (optional), followed by the area code
         (which is captured, so that it can be retained), followed by 15, which is the mobile token,
         which will be stripped if present. We expect the following combinations: 0AC15 and AC15
         (where the 0 and 15 will be stripped, and it will be transformed into 9AC), 0, and 15 (in
         the latter two cases we just strip the 0 or 15 as appropriate and leave the number as is.) -->
    <!-- http://www.itu.int/oth/T0202000009/en -->
    <!-- https://www.enacom.gob.ar/indicativos-de-servicio_p141 -->
    <!-- https://www.enacom.gob.ar/indicativos-interurbanos_p143 -->
    <!-- http://en.wikipedia.org/wiki/+54 -->
    <territory id="AR" countryCode="54" internationalPrefix="00" nationalPrefix="0"
               nationalPrefixForParsing="
                 0?(?:
                   (
                     11|
                     2(?:
                       2(?:
                         02?|
                         [13]|
                         2[13-79]|
                         4[1-6]|
                         5[2457]|
                         6[124-8]|
                         7[1-4]|
                         8[13-6]|
                         9[1267]
                       )|
                       3(?:
                         02?|
                         1[467]|
                         2[03-6]|
                         3[13-8]|
                         [49][2-6]|
                         5[2-8]|
                         [67]
                       )|
                       4(?:
                         7[3-578]|
                         9
                       )|
                       6(?:
                         [0136]|
                         2[24-6]|
                         4[6-8]?|
                         5[15-8]
                       )|
                       80|
                       9(?:
                         0[1-3]|
                         [19]|
                         2\d|
                         3[1-6]|
                         4[02568]?|
                         5[2-4]|
                         6[2-46]|
                         72?|
                         8[23]?
                       )
                     )|
                     3(?:
                       3(?:
                         2[79]|
                         6|
                         8[2578]
                       )|
                       4(?:
                         0[0-24-9]|
                         [12]|
                         3[5-8]?|
                         4[24-7]|
                         5[4-68]?|
                         6[02-9]|
                         7[126]|
                         8[2379]?|
                         9[1-36-8]
                       )|
                       5(?:
                         1|
                         2[1245]|
                         3[237]?|
                         4[1-46-9]|
                         6[2-4]|
                         7[1-6]|
                         8[2-5]?
                       )|
                       6[24]|
                       7(?:
                         [069]|
                         1[1568]|
                         2[15]|
                         3[145]|
                         4[13]|
                         5[14-8]|
                         7[2-57]|
                         8[126]
                       )|
                       8(?:
                         [01]|
                         2[15-7]|
                         3[2578]?|
                         4[13-6]|
                         5[4-8]?|
                         6[1-357-9]|
                         7[36-8]?|
                         8[5-8]?|
                         9[124]
                       )
                     )
                   )15
                 )?"
               nationalPrefixTransformRule="9$1" mobileNumberPortableRegion="true">
      <availableFormats>
        <!-- Format short numbers as a block. -->
        <numberFormat pattern="(\d{3})">
          <leadingDigits>
            0|
            1(?:
              0[0-35-7]|
              1[02-5]|
              2[015]|
              3[47]|
              4[478]
            )|
            911
          </leadingDigits>
          <format>$1</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{4})">
          <leadingDigits>[1-9]</leadingDigits>
          <format>$1-$2</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{4})">
          <leadingDigits>[2-8]</leadingDigits>
          <format>$1-$2</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{4})">
          <leadingDigits>[1-8]</leadingDigits>
          <format>$1-$2</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{2})(\d{4})" nationalPrefixFormattingRule="$NP$FG"
                      nationalPrefixOptionalWhenFormatting="true">
          <leadingDigits>
            2(?:
              2[024-9]|
              3[0-59]|
              47|
              6[245]|
              9[02-8]
            )|
            3(?:
              3[28]|
              4[03-9]|
              5[2-46-8]|
              7[1-578]|
              8[2-9]
            )
          </leadingDigits>
          <leadingDigits>
            2(?:
              [23]02|
              6(?:
                [25]|
                4[6-8]
              )|
              9(?:
                [02356]|
                4[02568]|
                72|
                8[23]
              )
            )|
            3(?:
              3[28]|
              4(?:
                [04679]|
                3[5-8]|
                5[4-68]|
                8[2379]
              )|
              5(?:
                [2467]|
                3[237]|
                8[2-5]
              )|
              7[1-578]|
              8(?:
                [2469]|
                3[2578]|
                5[4-8]|
                7[36-8]|
                8[5-8]
              )
            )|
            2(?:
              2[24-9]|
              3[1-59]|
              47
            )
          </leadingDigits>
          <leadingDigits>
            2(?:
              [23]02|
              6(?:
                [25]|
                4(?:
                  64|
                  [78]
                )
              )|
              9(?:
                [02356]|
                4(?:
                  [0268]|
                  5[2-6]
                )|
                72|
                8[23]
              )
            )|
            3(?:
              3[28]|
              4(?:
                [04679]|
                3[78]|
                5(?:
                  4[46]|
                  8
                )|
                8[2379]
              )|
              5(?:
                [2467]|
                3[237]|
                8[23]
              )|
              7[1-578]|
              8(?:
                [2469]|
                3[278]|
                5[56][46]|
                86[3-6]
              )
            )|
            2(?:
              2[24-9]|
              3[1-59]|
              47
            )|
            38(?:
              [58][78]|
              7[378]
            )|
            3(?:
              4[35][56]|
              58[45]|
              8(?:
                [38]5|
                54|
                76
              )
            )[4-6]
          </leadingDigits>
          <leadingDigits>
            2(?:
              [23]02|
              6(?:
                [25]|
                4(?:
                  64|
                  [78]
                )
              )|
              9(?:
                [02356]|
                4(?:
                  [0268]|
                  5[2-6]
                )|
                72|
                8[23]
              )
            )|
            3(?:
              3[28]|
              4(?:
                [04679]|
                3(?:
                  5(?:
                    4[0-25689]|
                    [56]
                  )|
                  [78]
                )|
                58|
                8[2379]
              )|
              5(?:
                [2467]|
                3[237]|
                8(?:
                  [23]|
                  4(?:
                    [45]|
                    60
                  )|
                  5(?:
                    4[0-39]|
                    5|
                    64
                  )
                )
              )|
              7[1-578]|
              8(?:
                [2469]|
                3[278]|
                54(?:
                  4|
                  5[13-7]|
                  6[89]
                )|
                86[3-6]
              )
            )|
            2(?:
              2[24-9]|
              3[1-59]|
              47
            )|
            38(?:
              [58][78]|
              7[378]
            )|
            3(?:
              454|
              85[56]
            )[46]|
            3(?:
              4(?:
                36|
                5[56]
              )|
              8(?:
                [38]5|
                76
              )
            )[4-6]
          </leadingDigits>
          <format>$1 $2-$3</format>
        </numberFormat>
        <!-- Formatting for geographic numbers (including those which can be dialled with a mobile token). -->
        <numberFormat pattern="(\d{2})(\d{4})(\d{4})" nationalPrefixFormattingRule="$NP$FG"
                      nationalPrefixOptionalWhenFormatting="true">
          <leadingDigits>1</leadingDigits>
          <format>$1 $2-$3</format>
        </numberFormat>
        <!-- Various non-geographic numbers, including UAN, premium rate but also some mobile
             ranges. We assume no local dialling is possible for these ranges. -->
        <numberFormat pattern="(\d{3})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>[68]</leadingDigits>
          <format>$1-$2-$3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{4})" nationalPrefixFormattingRule="$NP$FG"
                      nationalPrefixOptionalWhenFormatting="true">
          <leadingDigits>[23]</leadingDigits>
          <format>$1 $2-$3</format>
        </numberFormat>
        <numberFormat pattern="(\d)(\d{4})(\d{2})(\d{4})" nationalPrefixFormattingRule="$NP$FG">
          <leadingDigits>
            9(?:
              2[2-469]|
              3[3-578]
            )
          </leadingDigits>
          <leadingDigits>
            9(?:
              2(?:
                2[024-9]|
                3[0-59]|
                47|
                6[245]|
                9[02-8]
              )|
              3(?:
                3[28]|
                4[03-9]|
                5[2-46-8]|